#  Лабораторна робота "Обробка табличних даних засобами бібліотеки Pandas"

__Метою__ лабораторної роботи є вивчення технологій первинного аналізу даних в середовищі бібліотеки Pandas, а саме здобуття навичок:
- працювати з даними використовуючи мову Python та пакет Pandas
- робити передобробку даних
- знаходити прості закономірності у даних

## 1. Створення  DataFrame

__DataFrame__ — це двовимірна неоднорідна таблична структура даних із змінюваними розмірами з іменованими вісями (рядками та стовпцями)

In [11]:
# підключити бібліотеки Pandas та NumPy
import pandas as pd
import numpy as np

### ПРИКЛАДИ

In [12]:
# створити DataFrame з 1 колонкою з python-списка
df = pd.DataFrame(["Петя", "Вася", "Микола"])
print(df)
print(type(df))

        0
0    Петя
1    Вася
2  Микола
<class 'pandas.core.frame.DataFrame'>


In [13]:
# створити DataFrame з np-матриці розміром 10х10 випадкових чисел
mat = np.random.randint(100, 500, (10,10), dtype="int16")
print(mat)
df = pd.DataFrame(mat)
df

[[119 115 112 275 319 294 491 211 362 249]
 [323 396 199 331 339 381 247 122 437 198]
 [280 408 304 285 262 479 367 421 336 473]
 [136 341 463 468 417 137 161 451 468 144]
 [140 136 125 187 191 435 265 306 355 486]
 [295 322 344 375 171 403 116 382 134 335]
 [496 460 320 303 408 353 274 277 146 421]
 [492 391 279 225 279 278 404 254 489 374]
 [353 385 387 402 132 397 329 310 344 259]
 [321 171 397 149 392 492 356 408 446 101]]


0    1    2    3    4    5    6    7    8    9
0  119  115  112  275  319  294  491  211  362  249
1  323  396  199  331  339  381  247  122  437  198
2  280  408  304  285  262  479  367  421  336  473
3  136  341  463  468  417  137  161  451  468  144
4  140  136  125  187  191  435  265  306  355  486
5  295  322  344  375  171  403  116  382  134  335
6  496  460  320  303  408  353  274  277  146  421
7  492  391  279  225  279  278  404  254  489  374
8  353  385  387  402  132  397  329  310  344  259
9  321  171  397  149  392  492  356  408  446  101

In [14]:
# створити DataFrame з 2-мірного випадкового масиву з іменованими колонками
arr = np.random.random((5,3))
print(arr)
df = pd.DataFrame(arr, columns=["колонка 1", "колонка 2", "колонка 3"])
df

[[7.25577402e-01 4.39831234e-01 8.63852208e-01]
 [7.58467471e-01 4.58576016e-01 3.74414462e-01]
 [4.47213568e-01 2.73678684e-01 7.13811407e-01]
 [8.03080546e-01 3.73235751e-04 7.05697940e-01]
 [6.44907074e-01 6.21391093e-01 1.18949334e-01]]


колонка 1  колонка 2  колонка 3
0   0.725577   0.439831   0.863852
1   0.758467   0.458576   0.374414
2   0.447214   0.273679   0.713811
3   0.803081   0.000373   0.705698
4   0.644907   0.621391   0.118949

In [15]:
# створити DataFrame з python-словника в якому ключ - це ім'я, а значення - 
# це масив з 5-ти випадкових чисел з модифікованими індексами рядків
d = {
    "Петя": np.random.random(5),
    "Вася" : np.random.random(5),
    "Микола":np.random.random(5)
    }
a = pd.DataFrame(d, index=[10,20,30,40,50])

In [16]:
a

Петя      Вася    Микола
10  0.769244  0.813043  0.316516
20  0.967356  0.921623  0.979713
30  0.893973  0.915155  0.287178
40  0.263035  0.699583  0.516349
50  0.100105  0.909903  0.179859

In [17]:
# створити dataFrame з ітеруємого об'єкта
name = ["Вася", "Петя", "Микола"]
rik = [2001, 2000, 2003]
name_rik = list(zip(name, rik))
print(name_rik)
df = pd.DataFrame(name_rik, columns=["Ім'я", "Рік народження"])
df

[('Вася', 2001), ('Петя', 2000), ('Микола', 2003)]


Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

In [19]:
str(name_rik[2])

"('Микола', 2003)"

In [31]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    sep=<no_default>,
    delimiter=None,
    header='infer',
    names=<no_default>,
    index_col=None,
    usecols=None,
    squeeze=None,
    prefix=<no_default>,
    mangle_dupe_cols=True,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace=False,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    na_values=None,
    keep_default_na=True,
    na_filter=True,
    verbose=False,
    skip_blank_lines=True,
    parse_dates=None,
    infer_datetime_format=False,
    keep_date_col=False,
    date_parser=None,
    dayfirst=False,
    cache_dates=True,
    iterator=False,
    chunksize=None,
    compression: 'CompressionOptions' = 'infer',
    thousands=None,
    decimal: 'str' = '.',
    lineterminator=None,
    quotechar='"',
    quoting=0,
    doublequote=True,
    esc

In [33]:
!echo "Вася, 2001\nПетя, 2000,\nМикола,2003\n" > file.csv
!cat file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv("file.csv", names=["Ім'я", "Рік народження"])
df

'cat' is not recognized as an internal or external command,
operable program or batch file.


UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte

### ЗАВДАННЯ

In [34]:
# ЗАВДАННЯ 1.1: створити датафрейм з списку 10-ти простих чисел
df1_1 = pd.DataFrame([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
df1_1

0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [35]:
# ЗАВДАННЯ 1.2: створити датафрейм з матриці 5х6 випадкових чисел з плаваючою точкою
df1_2 = pd.DataFrame(np.random.rand(5,6))

ЗАВДАННЯ 1.3: створити  DataFrame наступного вигляду:

|ім'я | прізвище| рік народження | телефон
|:-----|:------|:-----:|:-------:
|Петро| Петров| 2000| 222-222-2222
|Іван| Іванов| 2002| 333-333-3333
|Степан| Степанов| 2001| 444-444-4444

In [36]:
df1_2

0         1         2         3         4         5
0  0.456077  0.736578  0.394918  0.389218  0.619752  0.124791
1  0.512979  0.357858  0.679287  0.852769  0.713928  0.890904
2  0.575627  0.805777  0.544558  0.648740  0.321188  0.775806
3  0.257816  0.313690  0.592188  0.781609  0.003718  0.481690
4  0.608741  0.688235  0.328758  0.664902  0.982060  0.211527

In [41]:
# ЗАВДАННЯ 1.4: створити датафрейм з 20 перших рядків excel-файлу, 
# який розташовано за адресою: 
# https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls
df1_4 = pd.read_csv("ЖУРНАЛ ФІТ 3 курс.csv", nrows=20)
df1_4


FileNotFoundError: [Errno 2] No such file or directory: 'ЖУРНАЛ ФІТ 3 курс.csv'

## 2. Інспектування DataFrame

__Інспектування__ - це процедури вивчення внутрішньої структури даних та вмісту датафрейма

### ПРИКЛАДИ

In [42]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [43]:
# отримати загальну інформацію про датасет
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [44]:
# вивести перші 3 рядкі
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [45]:
# вивести останні 2 рядки
titanic.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

In [46]:
# отримати імена колонок
col_names = titanic.columns
print(col_names)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [47]:
# вивести загальну статистику датасету - числові поля
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [48]:
# вивести статитсику текстового поля `Sex` 
titanic['Sex'].describe()

count      891
unique       2
top       male
freq       577
Name: Sex, dtype: object

In [49]:
# перевірити тип колонки датасету
type(titanic['Age'])

pandas.core.series.Series

In [50]:
# вивести перші 10 рядків деяких колонок
cols = ["Name", "Age", "Sex"]
titanic[cols].head(10)

Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male
5                                   Moran, Mr. James   NaN    male
6                            McCarthy, Mr. Timothy J  54.0    male
7                     Palsson, Master. Gosta Leonard   2.0    male
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0  female

In [51]:
# вивести рядки з 100 по 110
titanic[100:110]

PassengerId  Survived  Pclass                              Name     Sex  \
100          101         0       3           Petranec, Miss. Matilda  female   
101          102         0       3  Petroff, Mr. Pastcho ("Pentcho")    male   
102          103         0       1         White, Mr. Richard Frasar    male   
103          104         0       3        Johansson, Mr. Gustaf Joel    male   
104          105         0       3    Gustafsson, Mr. Anders Vilhelm    male   
105          106         0       3             Mionoff, Mr. Stoytcho    male   
106          107         1       3  Salkjelsvik, Miss. Anna Kristine  female   
107          108         1       3            Moss, Mr. Albert Johan    male   
108          109         0       3                   Rekic, Mr. Tido    male   
109          110         1       3               Moran, Miss. Bertha  female   

      Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
100  28.0      0      0   349245   7.8958   NaN        S  
101   NaN      0      0   349215   7.8958   NaN        S  
102  21.0      0      1    35281  77.2875   D26        S  
103  33.0      0      0     7540   8.6542   NaN        S  
104  37.0      2      0  3101276   7.9250   NaN        S  
105  28.0      0      0   349207   7.8958   NaN        S  
106  21.0      0      0   343120   7.6500   NaN        S  
107   NaN      0      0   312991   7.7750   NaN        S  
108  38.0      0      0   349249   7.8958   NaN        S  
109   NaN      1      0   371110  24.1500   NaN        Q

In [52]:
# вивести тільки чоловіків
cond = titanic["Sex"] == "male"
titanic[cond]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[577 rows x 12 columns]

In [53]:
# вивести рядки в яких пропущено значення поля `Age`
cond = titanic['Age'].isna()
titanic[cond].head(3)

PassengerId  Survived  Pclass                          Name     Sex  Age  \
5             6         0       3              Moran, Mr. James    male  NaN   
17           18         1       2  Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3       Masselmani, Mrs. Fatima  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583   NaN        Q  
17      0      0  244373  13.0000   NaN        S  
19      0      0    2649   7.2250   NaN        C

In [54]:
# вивести рядки з пасажирами вік яких з 30 до 50 років
cond = titanic['Age'].between(30, 50)
titanic[cond]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
13            14         0       3   
18            19         0       3   
..           ...       ...     ...   
872          873         0       1   
873          874         0       3   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
..                                                 ...     ...   ...    ...   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
4        0    373450   8.0500          NaN        S  
13       5    347082  31.2750          NaN        S  
18       0    345763  18.0000          NaN        S  
..     ...       ...      ...          ...      ...  
872      0       695   5.0000  B51 B53 B55        S  
873      0    345765   9.0000          NaN        S  
881      0    349257   7.8958          NaN        S  
885      5    382652  29.1250          NaN        Q  
890      0    370376   7.7500          NaN        Q  

[266 rows x 12 columns]

### ЗАВДАННЯ

In [89]:
# ЗАВДАННЯ 2.1: вивести характеристики датасету `titanic`
titanic.info()
titanic.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [93]:
# ЗАВДАННЯ 2.2: вивести статистичні параметри полів `Age` та `Fare` датасету `titanic`
titanic["Age"].describe()
titanic["Fare"].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [94]:
# ЗАВДАННЯ 2.3: пірахувати кількість записів в яких заповнені усі показчики
titanic[~titanic.isnull().any(axis=1)]  

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [95]:
# ЗАВДАННЯ 2.4: пірахувати кількість виживших (survived=1) пасажирів жиночої статі (Sex=`female`)
titanic[(titanic.Sex=="female")&(titanic.Survived==1)].shape[0]

233

## 3. Перетворення датафреймів

__Перетворення__ - це сукупність операцій та методів для зміни структури та вмісту датафрейму та окремих його елементів

### ПРИКЛАДИ

In [96]:
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}

df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [62]:
# типи колонок та елементів в колонці
print(df["рейтинг"].dtype)
print(type(df['рейтинг']))

object
<class 'pandas.core.series.Series'>


In [63]:
# Перетворити тип колонки (показчика) 'рейтинг' в ціле числове
df['рейтинг'] = df['рейтинг'].astype("int8")
print(df["рейтинг"].dtype)

int8


In [64]:
# додати колонку "адреса"
df["адреса"] = ["Київ", "Бровари", "Фастів"]
df

ім'я  вік  рейтинг   адреса
0  Петя   22       10     Київ
1  Вася  200        3  Бровари
2  Галя   21        2   Фастів

In [65]:
#  збільшити значення "рейтинг" на 3
df['рейтинг'] = df['рейтинг'] + 3
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася  200        6  Бровари
2  Галя   21        5   Фастів

In [66]:
# виправити значення параметру 'вік' для імені 'Вася'
df.loc[1, "вік"] = 20
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася   20        6  Бровари
2  Галя   21        5   Фастів

In [67]:
# видалити колонку `вік'
df.drop(columns='вік', inplace=True)
df

ім'я  рейтинг   адреса
0  Петя       13     Київ
1  Вася        6  Бровари
2  Галя        5   Фастів

In [68]:
# вивести 5 перших рядків датафрейму
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [69]:
# вивести 3 випадкових рядки датафрейму
titanic.sample(3)

PassengerId  Survived  Pclass                                   Name  \
103          104         0       3             Johansson, Mr. Gustaf Joel   
246          247         0       3  Lindahl, Miss. Agda Thorilda Viktoria   
806          807         0       1                 Andrews, Mr. Thomas Jr   

        Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked  
103    male  33.0      0      0    7540  8.6542   NaN        S  
246  female  25.0      0      0  347071  7.7750   NaN        S  
806    male  39.0      0      0  112050  0.0000   A36        S

In [70]:
# відсортувати dataframe `titanic` за віком пасажиров
titanic.sort_values('Age')

PassengerId  Survived  Pclass                                      Name  \
803          804         1       3           Thomas, Master. Assad Alexander   
755          756         1       2                 Hamalainen, Master. Viljo   
644          645         1       3                    Baclini, Miss. Eugenie   
469          470         1       3             Baclini, Miss. Helene Barbara   
78            79         1       2             Caldwell, Master. Alden Gates   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
803    male  0.42      0      1        2625   8.5167   NaN        C  
755    male  0.67      1      1      250649  14.5000   NaN        S  
644  female  0.75      2      1        2666  19.2583   NaN        C  
469  female  0.75      2      1        2666  19.2583   NaN        C  
78     male  0.83      0      2      248738  29.0000   NaN        S  
..      ...   ...    ...    ...         ...      ...   ...      ...  
859    male   NaN      0      0        2629   7.2292   NaN        C  
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male   NaN      0      0      345777   9.5000   NaN        S  
878    male   NaN      0      0      349217   7.8958   NaN        S  
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S  

[891 rows x 12 columns]

In [71]:
# перейменувати значення в `Embarked` стовпчику:
# С - Cherbourg
# Q - Queenstown
# S - Southampton
titanic['Embarked'].replace({"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"},
                           inplace=True)
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin     Embarked  
0        0         A/5 21171   7.2500   NaN  Southampton  
1        0          PC 17599  71.2833   C85    Cherbourg  
2        0  STON/O2. 3101282   7.9250   NaN  Southampton  
3        0            113803  53.1000  C123  Southampton  
4        0            373450   8.0500   NaN  Southampton  
..     ...               ...      ...   ...          ...  
886      0            211536  13.0000   NaN  Southampton  
887      0            112053  30.0000   B42  Southampton  
888      2        W./C. 6607  23.4500   NaN  Southampton  
889      0            111369  30.0000  C148    Cherbourg  
890      0            370376   7.7500   NaN   Queenstown  

[891 rows x 12 columns]

In [72]:
# підрахувати кількість пасажирів 1-го класу (Pclass=1)
cond = titanic['Pclass'] == 1
kol_pass = titanic[cond]['PassengerId'].count()
kol_pass

216

In [73]:
# замінити відсутні номери кают на ''
titanic.fillna({"Cabin": "***"}, inplace=True)
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin     Embarked  
0      0         A/5 21171   7.2500   ***  Southampton  
1      0          PC 17599  71.2833   C85    Cherbourg  
2      0  STON/O2. 3101282   7.9250   ***  Southampton

In [74]:
# видалити рядки в яких є відсутні значення 
titanic.dropna(axis=0, how='any', inplace=True)
titanic.shape

(712, 12)

### ЗАВДАННЯ

In [97]:
# ЗАВДАННЯ 3.1: створити датафрейм з словника d
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}
df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [98]:
# ЗАВДАННЯ 3.2: додати до `df` стовбчик з показчиком 
# `рік завершення школи` = [2018, 2020, 200]
df["рік завершення школи"] = [2018, 2020, 200]
print(df)

   ім'я  вік рейтинг  рік завершення школи
0  Петя   22      10                  2018
1  Вася  200       3                  2020
2  Галя   21       2                   200


In [99]:
# ЗАВДАННЯ 3.3: виправити 'рік завершення школи' з 200 на 2020
df.loc[2, "рік завершення школи"] = 2020
print(df)

   ім'я  вік рейтинг  рік завершення школи
0  Петя   22      10                  2018
1  Вася  200       3                  2020
2  Галя   21       2                  2020


In [100]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [101]:
# ЗАВДАННЯ 3.4: вивести з датасету `titanic` останні 10 записів 
titanic.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [102]:
# ЗАВДАННЯ 3.5: вибрати з датасету `titanic` рядки з пасажирами чоловічої статі віком 
# від 20 до 30 років, які подорожували 2 класом
titanic[(titanic.Sex == "male") & (titanic.Pclass == 2) & (titanic.Age.between(20,30))]

PassengerId  Survived  Pclass  \
72            73         0       2   
117          118         0       2   
120          121         0       2   
134          135         0       2   
135          136         0       2   
178          179         0       2   
213          214         0       2   
219          220         0       2   
221          222         0       2   
234          235         0       2   
242          243         0       2   
308          309         0       2   
342          343         0       2   
343          344         0       2   
361          362         0       2   
398          399         0       2   
418          419         0       2   
529          530         0       2   
551          552         0       2   
562          563         0       2   
619          620         0       2   
655          656         0       2   
658          659         0       2   
666          667         0       2   
685          686         0       2   
728          729         0       2   
733          734         0       2   
734          735         0       2   
848          849         0       2   
861          862         0       2   
864          865         0       2   
883          884         0       2   
886          887         0       2   

                                           Name   Sex   Age  SibSp  Parch  \
72                         Hood, Mr. Ambrose Jr  male  21.0      0      0   
117             Turpin, Mr. William John Robert  male  29.0      1      0   
120                 Hickman, Mr. Stanley George  male  21.0      2      0   
134              Sobey, Mr. Samuel James Hayden  male  25.0      0      0   
135                          Richard, Mr. Emile  male  23.0      0      0   
178                          Hale, Mr. Reginald  male  30.0      0      0   
213                 Givard, Mr. Hans Kristensen  male  30.0      0      0   
219                          Harris, Mr. Walter  male  30.0      0      0   
221                        Bracken, Mr. James H  male  27.0      0      0   
234           Leyson, Mr. Robert William Norman  male  24.0      0      0   
242             Coleridge, Mr. Reginald Charles  male  29.0      0      0   
308                         Abelson, Mr. Samuel  male  30.0      1      0   
342                  Collander, Mr. Erik Gustaf  male  28.0      0      0   
343  Sedgwick, Mr. Charles Frederick Waddington  male  25.0      0      0   
361                   del Carlo, Mr. Sebastiano  male  29.0      1      0   
398                            Pain, Dr. Alfred  male  23.0      0      0   
418                  Matthews, Mr. William John  male  30.0      0      0   
529                 Hocking, Mr. Richard George  male  23.0      2      1   
551                 Sharp, Mr. Percival James R  male  27.0      0      0   
562                  Norman, Mr. Robert Douglas  male  28.0      0      0   
619                         Gavey, Mr. Lawrence  male  26.0      0      0   
655                   Hickman, Mr. Leonard Mark  male  24.0      2      0   
658                Eitemiller, Mr. George Floyd  male  23.0      0      0   
666                 Butler, Mr. Reginald Fenton  male  25.0      0      0   
685      Laroche, Mr. Joseph Philippe Lemercier  male  25.0      1      2   
728             Bryhl, Mr. Kurt Arnold Gottfrid  male  25.0      1      0   
733                  Berriman, Mr. William John  male  23.0      0      0   
734                Troupiansky, Mr. Moses Aaron  male  23.0      0      0   
848                           Harper, Rev. John  male  28.0      0      1   
861                 Giles, Mr. Frederick Edward  male  21.0      1      0   
864                      Gill, Mr. John William  male  24.0      0      0   
883               Banfield, Mr. Frederick James  male  28.0      0      0   
886                       Montvila, Rev. Juozas  male  27.0      0      0   

               Ticket     Fare Cabin Embarked  
72       S.O.C. 14879  73.5000   NaN        S

In [103]:
# ЗАВДАННЯ 3.6: видалити з датасету `titanic` рядки з пасажирами у яких відсутня
# вартість (fare) квітка
df = titanic.drop(titanic[titanic.Fare.isna()].index)
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [104]:
# ЗАВДАННЯ 3.7: підрахувати середню вартість квитка у каютах 1-го класу
avg_price = titanic[titanic.Pclass == 1].Fare.mean()
print(avg_price)

84.15468749999992


## 4. Агрегація датафреймів

__Агрегація__ - це функції отримання агрегованих даних шляхом групування об'єктів датафрейма 

### ПРИКЛАДИ

In [83]:
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [84]:
# підрахувати середній вік пасажирів по класам кают
group_by_class = titanic.groupby(["Pclass"])
avg_age = group_by_class["Age"].mean()
print(avg_age)

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64


In [85]:
# підрахувати кількість чоловіків та жінок по класам кают
man_woman_count = titanic.groupby(["Pclass", "Sex"])["Sex"].count()
man_woman_count

Pclass  Sex   
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: Sex, dtype: int64

In [86]:
# створити таблицю в якій підраховано середню вартість білетів (Fare) в залежності
# від місця посадки (Embarked) по класам кают
tickets_cost = titanic.pivot_table(values="Fare", index="Pclass", columns="Embarked",
                   aggfunc=np.mean)
tickets_cost

Embarked           C          Q          S
Pclass                                    
1         104.718529  90.000000  70.364862
2          25.358335  12.350000  20.327439
3          11.214083  11.183393  14.644083

### ЗАВДАННЯ

In [105]:
# ЗАВДАННЯ 4.1: отримати відомості про максимальний вік жінок та чоловіків
max_age = titanic.groupby(["Sex"])["Age"].max()
print(max_age)

Sex
female    63.0
male      80.0
Name: Age, dtype: float64


___ЗАВДАННЯ 4.2___

на основі даних з `titanic` побудувати таблицю наступного вигляду:

Pclass  |Male  | Female
--------|------|-------
1  | ... | ...
2  | ... | ...
3  | ... | ...

де замість `...` повинно бути кількість виживших (Survived) чоловіків та жінок відповідно

In [106]:
surv_table = titanic.pivot_table(values="Survived",index="Pclass",columns="Sex", aggfunc=np.sum)
surv_table = surv_table.reset_index().rename_axis(None,axis=1)
surv_table

Pclass  female  male
0       1      91    45
1       2      70    17
2       3      72    47